server:
  port: 8080

chicken:
  roles:
    organizer: achang
    tutor: thull

spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: user

        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token

  flyway:
    schemas: chicken
    create-schemas: true
    url: jdbc:mariadb://localhost:3306/
    user: root
    password: iamchicken

  datasource:
    url: jdbc:mariadb://localhost:3306/chicken
    username: root
    password: iamchicken

#logging:
#  level:
#    root: debug